openapi: 3.0.7
info:
  title: user-api
  version: '0.0.1'
tags:
  - name: greetings
    description: Greetings
paths:
  /greetings:
    get:
      tags:
        - greetings
      summary: sayHello
      operationId: sayHello
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      security:
        - bearerAuth: [ ]
components:
  securitySchemes:
    bearerAuth:
      name: Authorization
      type: apiKey
      in: header
      description: ''
